// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OneHope.API.Models;

#nullable disable

namespace OneHope.API.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20231009131603_MigracionInicial")]
    partial class MigracionInicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OneHope.API.Models.Alquiler", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("ApellidosCliente")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DireccionEnvio")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("nvarchar(75)");

                    b.Property<string>("EmailCliente")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaAlquiler")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaFinAlquiler")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInAlquiler")
                        .HasColumnType("datetime2");

                    b.Property<int>("MetodoPagoID")
                        .HasColumnType("int");

                    b.Property<string>("NombreCliente")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("TelefonoCliente")
                        .HasColumnType("int");

                    b.Property<float>("Total")
                        .HasColumnType("real");

                    b.HasKey("ID");

                    b.HasIndex("MetodoPagoID");

                    b.ToTable("Alquilers");
                });

            modelBuilder.Entity("OneHope.API.Models.LineaAlquiler", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("AlquilerID")
                        .HasColumnType("int");

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("PortatilID")
                        .HasColumnType("int");

                    b.Property<float>("PortatilPrecioAlq")
                        .HasColumnType("real");

                    b.HasKey("ID");

                    b.HasAlternateKey("AlquilerID", "PortatilID");

                    b.HasIndex("PortatilID");

                    b.ToTable("LineasAlquiler");
                });

            modelBuilder.Entity("OneHope.API.Models.Marca", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("nvarchar(75)");

                    b.HasKey("ID");

                    b.ToTable("Marcas");
                });

            modelBuilder.Entity("OneHope.API.Models.MetodoPago", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("TipoMetodoPago")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("MetodoPago");

                    b.HasDiscriminator<string>("TipoMetodoPago").HasValue("MetodoPago");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("OneHope.API.Models.Portatil", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("MarcaID")
                        .HasColumnType("int");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("nvarchar(75)");

                    b.Property<float>("PrecioAlq")
                        .HasColumnType("real");

                    b.Property<float>("PrecioCompra")
                        .HasColumnType("real");

                    b.Property<float>("PrecioCoste")
                        .HasColumnType("real");

                    b.Property<int>("ProcesadorID")
                        .HasColumnType("int");

                    b.Property<int>("RAMID")
                        .HasColumnType("int");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<int>("StockAlq")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("MarcaID");

                    b.HasIndex("ProcesadorID");

                    b.HasIndex("RAMID");

                    b.ToTable("Portatiles");
                });

            modelBuilder.Entity("OneHope.API.Models.Procesador", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("ID");

                    b.ToTable("Procesadores");
                });

            modelBuilder.Entity("OneHope.API.Models.RAM", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("ID");

                    b.ToTable("RAMs");
                });

            modelBuilder.Entity("OneHope.API.Models.PayPal", b =>
                {
                    b.HasBaseType("OneHope.API.Models.MetodoPago");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Telefono")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("PayPal");
                });

            modelBuilder.Entity("OneHope.API.Models.TarjetaCredito", b =>
                {
                    b.HasBaseType("OneHope.API.Models.MetodoPago");

                    b.Property<int>("CCV")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCaducidad")
                        .HasColumnType("datetime2");

                    b.Property<int>("NumTC")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Tarjeta");
                });

            modelBuilder.Entity("OneHope.API.Models.Transferencia", b =>
                {
                    b.HasBaseType("OneHope.API.Models.MetodoPago");

                    b.Property<int>("NumeroCuenta")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Transferencia");
                });

            modelBuilder.Entity("OneHope.API.Models.Alquiler", b =>
                {
                    b.HasOne("OneHope.API.Models.MetodoPago", "MetodoPago")
                        .WithMany()
                        .HasForeignKey("MetodoPagoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MetodoPago");
                });

            modelBuilder.Entity("OneHope.API.Models.LineaAlquiler", b =>
                {
                    b.HasOne("OneHope.API.Models.Alquiler", "Alquiler")
                        .WithMany("LineasAlquiler")
                        .HasForeignKey("AlquilerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OneHope.API.Models.Portatil", "Portatil")
                        .WithMany("LineasAlquiler")
                        .HasForeignKey("PortatilID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alquiler");

                    b.Navigation("Portatil");
                });

            modelBuilder.Entity("OneHope.API.Models.Portatil", b =>
                {
                    b.HasOne("OneHope.API.Models.Marca", "Marca")
                        .WithMany("Portatiles")
                        .HasForeignKey("MarcaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OneHope.API.Models.Procesador", "Procesador")
                        .WithMany("Portatiles")
                        .HasForeignKey("ProcesadorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OneHope.API.Models.RAM", "RAM")
                        .WithMany("Portatiles")
                        .HasForeignKey("RAMID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Marca");

                    b.Navigation("Procesador");

                    b.Navigation("RAM");
                });

            modelBuilder.Entity("OneHope.API.Models.Alquiler", b =>
                {
                    b.Navigation("LineasAlquiler");
                });

            modelBuilder.Entity("OneHope.API.Models.Marca", b =>
                {
                    b.Navigation("Portatiles");
                });

            modelBuilder.Entity("OneHope.API.Models.Portatil", b =>
                {
                    b.Navigation("LineasAlquiler");
                });

            modelBuilder.Entity("OneHope.API.Models.Procesador", b =>
                {
                    b.Navigation("Portatiles");
                });

            modelBuilder.Entity("OneHope.API.Models.RAM", b =>
                {
                    b.Navigation("Portatiles");
                });
#pragma warning restore 612, 618
        }
    }
}
